name: static

# 触发条件
on:
  workflow_dispatch:

  schedule:
   - cron: '0 10 * * *'
   #- cron: '0 1,10 * * *'
  #  实际时间：9:00	18:00  早9点高峰，排队老是到10点半左右
  # 表达式生成  https://crontab.guru/

jobs:
  deploy:
# 基本系统配置
    runs-on: ubuntu-latest
    steps:
    - name: 迁出代码
      uses: actions/checkout@v4
    - name: 安装Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10' 
    - name: 设置时区
      run: sudo timedatectl set-timezone 'Asia/Shanghai'
      
# 安装依赖和工具
    - name: 安装依赖和工具
      run: |
        pip install -r ./utils/requirements.txt
        python ./utils/tools.py

# 执行任务        
    - name: 执行任务 - 1.获取订阅节点
      run: |
        python ./utils/staticSub/fetch.py
    - name: 执行任务 - 2.测速
      run: |
       python ./utils/staticSub/speedtest.py
       python ./utils/clashspeedtest/main.py
    - name: 执行任务 - 3.log
      run: |
       python ./utils/subConvert/log.py 'static sub'
# 提交           
    - name: 提交更改
      run: |                 
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git pull origin main
        git add ./sub
        git commit -m "$(date '+%Y-%m-%d %H:%M:%S') static sub update"
    - name: 推送更改
      uses:  ad-m/github-push-action@master
      with:
        branch: main

    - name: Pushes to proxies
      uses: rxsweet/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.ACTIONS_USE }}
      with:
        source_file: 'sub/'
        destination_repo: 'rxsweet/proxies'
        user_email: 'actions@github.com'
        user_name: 'GitHub Actions'
        commit_message: 'static sub update'
