name: mining

# 触发条件
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["collect TG sub sources"]
    types: [completed]
#  schedule:
#   - cron: '25 5,13,23 * * *'
# 实际时间： 7:25, 13：25, 21:25
# 表达式生成  https://crontab.guru/

 
jobs:
  fetch:
# 系统设置开始
    runs-on: ubuntu-latest
    steps:
    - name: 迁出代码
      uses: actions/checkout@v4
    - name: 安装Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10' 
    - name: 加载缓存
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/run_in_Actions/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: 设置时区
      run: sudo timedatectl set-timezone 'Asia/Shanghai'
# 系统设置结束

# 安装依赖和工具
    - name: 安装依赖
      run: |
        pip install -r ./utils/requirements.txt
        python ./utils/tools.py
#执行任务        
    - name: 执行任务 - 1.check urllist
      run: |
        python ./utils/airport/mining/check.py
    - name: 执行任务 - 2.urllist to sub
      run:
       python ./utils/airport/mining/urllist2sub.py
    - name: 执行任务 - 3.speedtest
      run: |
        python ./utils/airport/mining/speedtest.py
        python ./utils/clashspeedtest/main.py
    #- name: 执行任务 - 4.fetchFreeAirport
      #run: |
        #python ./utils/airport/free/main.py
        #python ./utils/airport/free/goodToClash.py
    - name: 执行任务 - 5.log
      run:
       python ./utils/subConvert/log.py 'mining'
#提交，推送
    - name: Commit
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git pull origin main
        git add ./utils/airport/mining/
        git add ./sub/
        git commit -m "$(date '+%Y-%m-%d %H:%M:%S') mining airport done"
        
    - name: 推送更改
      uses:  ad-m/github-push-action@master
      with:
    #     github_token: ${{ secrets.TOKEN }}
         branch: main

    - name: Pushes to proxies
      uses: rxsweet/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{secrets.ACTIONS_USE}}
      with:
        source_file: 'sub/'
        destination_repo: 'rxsweet/proxies'
        user_email: 'actions@github.com'
        user_name: 'GitHub Actions'
        commit_message: 'mining airport done'
