name: mining

# 触发条件
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["collect TG sub sources"]
    types: [completed]
#  schedule:
#   - cron: '25 5,13,23 * * *'
# 实际时间： 7:25, 13：25, 21:25
# 表达式生成  https://crontab.guru/

permissions: write-all

jobs:
  mining:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: 设置时区
      run: sudo timedatectl set-timezone 'Asia/Shanghai'
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'

# 安装依赖和工具
    - name: 安装依赖
      run: |
        pip install -r ./utils/requirements.txt
        
#执行任务        
    - name: 执行任务 - 1.check urllist
      run: |
        python ./utils/airport/mining/mining_check.py
    - name: 执行任务 - 2.collect nodes
      run: |
        python ./utils/subconvert.py    './utils/airport/mining/mining_config.yaml'  'config'
        python ./utils/subconvert.py    './sub/sources/miningAll.yaml'  'base64' './sub/mining64.txt'
        python ./utils/subconvert.py    './sub/sources/miningAll.yaml'  'clash' './sub/mining.yaml'
    - name: 执行任务 - 3.log
      run:
        python ./utils/subConvert/log.py 'mining'
#提交，推送
    - name: Commit
      id: commit
      continue-on-error: true
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git pull origin main
        git add ./utils/airport/mining/
        git add ./sub/
        git commit -m "$(date '+%Y-%m-%d %H:%M:%S') mining airport done"
        git pull --rebase
    - name: 推送更改
      uses:  ad-m/github-push-action@master
      with:
        branch: main
    - name: Pushes to proxies
      uses: rxsweet/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.ACTIONS_USE }}
      with:
        source_file: 'sub/'
        destination_repo: 'rxsweet/proxies'
        user_email: 'actions@github.com'
        user_name: 'GitHub Actions'
        commit_message: 'mining airport done'
